import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navber";
import Footer from "@/components/Footer";
import Preloader from "./loading";
import InitialLoader from "@/components/InitialLoader";
import ScrollToTop from "@/components/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MatrixLab - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0d2e2d]`} // ব্যাকগ্রাউন্ড কালার দেওয়া হলো
      >
        <InitialLoader/>
        <Preloader/>
        <ScrollToTop/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}